In [1]:
# Import dependencies

import pandas as pd
import numpy as np

In [2]:
# Read in CSV files from FanGraphs (exported directly from site daily)

# Files contain pitching and hitting stats from two different time periods:
    # - Beginning of 2023 season - present ("year")
    # - Beginning of 2024 season - present ("season")
    
# Filtered stats include:
    # - Pitching stats vs. left- and right-handed batters the first time through the order
    # - Batting stats vs. left- and right-handed pitchers
    
pitching_vs_left_year_df = pd.read_csv('pitching_vs_left_year.csv')
pitching_vs_right_year_df = pd.read_csv('pitching_vs_right_year.csv')
pitching_vs_left_season_df = pd.read_csv('pitching_vs_left_season.csv')
pitching_vs_right_season_df = pd.read_csv('pitching_vs_right_season.csv')
batting_vs_left_year_df = pd.read_csv('batting_vs_left_year.csv')
batting_vs_right_year_df = pd.read_csv('batting_vs_right_year.csv')
batting_vs_left_season_df = pd.read_csv('batting_vs_left_season.csv')
batting_vs_right_season_df = pd.read_csv('batting_vs_right_season.csv')

# MLB season CSV contains league-wide stats from 2024 season to later compare K rate with home plate umpire's career K rate

mlb_season_df = pd.read_csv('MLB_season.csv')

In [3]:
# Create new columns:
    # - K Rate column for both pitchers and batters
    # - Opponent on-base percentage column for pitchers
    # - On-base percentage column for batters

pitching_vs_left_year_df['K_Rate'] = pitching_vs_left_year_df['SO'] / pitching_vs_left_year_df['TBF']
pitching_vs_right_year_df['K_Rate'] = pitching_vs_right_year_df['SO'] / pitching_vs_right_year_df['TBF']
pitching_vs_left_season_df['K_Rate'] = pitching_vs_left_season_df['SO'] / pitching_vs_left_season_df['TBF']
pitching_vs_right_season_df['K_Rate'] = pitching_vs_right_season_df['SO'] / pitching_vs_right_season_df['TBF']
pitching_vs_left_year_df['Opp_OBP'] = (pitching_vs_left_year_df['BB'] + pitching_vs_left_year_df['H']) / pitching_vs_left_year_df['TBF']
pitching_vs_right_year_df['Opp_OBP'] = (pitching_vs_right_year_df['BB'] + pitching_vs_right_year_df['H']) / pitching_vs_right_year_df['TBF']
pitching_vs_left_season_df['Opp_OBP'] = (pitching_vs_left_season_df['BB'] + pitching_vs_left_season_df['H']) / pitching_vs_left_season_df['TBF']
pitching_vs_right_season_df['Opp_OBP'] = (pitching_vs_right_season_df['BB'] + pitching_vs_right_season_df['H']) / pitching_vs_right_season_df['TBF']
batting_vs_left_year_df['K_Rate'] = batting_vs_left_year_df['SO'] / batting_vs_left_year_df['PA']
batting_vs_right_year_df['K_Rate'] = batting_vs_right_year_df['SO'] / batting_vs_right_year_df['PA']
batting_vs_right_season_df['K_Rate'] = batting_vs_right_season_df['SO'] / batting_vs_right_season_df['PA']
batting_vs_left_season_df['K_Rate'] = batting_vs_left_season_df['SO'] / batting_vs_left_season_df['PA']
batting_vs_left_year_df['OBP'] = (batting_vs_left_year_df['H'] + batting_vs_left_year_df['BB'] + batting_vs_left_year_df['HBP']) / batting_vs_left_year_df['PA']
batting_vs_right_year_df['OBP'] = (batting_vs_right_year_df['H'] + batting_vs_right_year_df['BB'] + batting_vs_right_year_df['HBP']) / batting_vs_right_year_df['PA']
batting_vs_right_season_df['OBP'] = (batting_vs_right_season_df['H'] + batting_vs_right_season_df['BB'] + batting_vs_right_season_df['HBP']) / batting_vs_right_season_df['PA']
batting_vs_left_season_df['OBP'] = (batting_vs_left_season_df['H'] + batting_vs_left_season_df['BB'] + batting_vs_left_season_df['HBP']) / batting_vs_left_season_df['PA']
mlb_season_df['K_Rate'] = mlb_season_df['SO'] / mlb_season_df['TBF']

# Display example pitching DataFrame (pitching stats the first time through the order vs. left-handed batters during the 2024 season)

pitching_vs_left_season_df.head()

,Season,Name,Tm,G,TBF,ERA,H,2B,3B,R,...,IBB,HBP,SO,AVG,OBP,SLG,wOBA,playerId,K_Rate,Opp_OBP
0,Total,Adam Ottavino,NYM,31,55,5.250000,11,2,1,8,...,0,2,16,0.239130,0.345455,0.456522,0.348188,1247,0.290909,0.309091
1,Total,Matt Moore,LAA,32,57,5.926829,10,1,0,10,...,0,0,9,0.200000,0.298246,0.460000,0.329402,1890,0.157895,0.298246
2,Total,Lance Lynn,STL,17,81,6.230769,17,5,0,15,...,0,1,24,0.242857,0.345679,0.528571,0.375912,2520,0.296296,0.333333
3,Total,Kenley Jansen,BOS,26,58,1.227273,12,2,0,2,...,1,0,18,0.230769,0.293103,0.269231,0.248079,3096,0.310345,0.293103
4,Total,Max Scherzer,TEX,3,13,0.000000,0,0,0,0,...,0,0,3,0.000000,0.076923,0.000000,0.053180,3137,0.230769,0.076923

In [4]:
# Display example batting DataFrame (batting stats vs. left-handed pitchers since the beginning of the 2023 season)

batting_vs_left_year_df.head()

,Season,Name,Tm,G,PA,AB,H,1B,2B,3B,...,HBP,SF,SH,GDP,SB,CS,AVG,playerId,K_Rate,OBP
0,Total,Miguel Cabrera,DET,47,96,83,22,17,5,0,...,1,1,0,2,0,0,0.265060,1744,0.239583,0.354167
1,Total,David Peralta,2 Tms,36,44,41,13,11,2,0,...,2,0,0,1,0,0,0.317073,2136,0.250000,0.363636
2,Total,Adam Wainwright,STL,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0.000000,2233,0.000000,0.000000
3,Total,Carlos Santana,3 Tms,116,242,214,59,36,12,0,...,1,2,0,4,2,0,0.275701,2396,0.144628,0.351240
4,Total,Nelson Cruz,SDP,37,86,80,20,14,3,0,...,1,1,0,1,0,0,0.250000,2434,0.325581,0.290698

In [5]:
# Merge pitching DataFrames together and format columns 

pitchers_combined_df = pd.merge(pitching_vs_left_year_df, pitching_vs_right_year_df, on='Name', how='outer')
pitchers_combined_df = pitchers_combined_df.rename(columns={'Opp_OBP_x': 'Year_Opp_OBP_LHH', 'Opp_OBP_y': 'Year_Opp_OBP_RHH', 'K_Rate_x' : 'Year_K%_LHH', 'K_Rate_y' : 'Year_K%_RHH'})
pitchers_combined_df = pd.merge(pitchers_combined_df, pitching_vs_left_season_df, on='Name', how='outer')
pitchers_combined_df = pitchers_combined_df.rename(columns={'Opp_OBP': 'Season_Opp_OBP_LHH', 'K_Rate' : 'Season_K%_LHH'})
pitchers_combined_df = pitchers_combined_df.drop(columns=['playerId_x','Season_x', 'Season_y', 'Tm_x', 'Tm_y', 'G_x', 'G_y', 'TBF_x', 'TBF_y', 'ERA_x', 'ERA_y', 'H_x', 'H_y', '2B_x', '2B_y', '3B_x', '3B_y', 'R_x', 'R_y', 'ER_x', 'ER_y', 'HR_x', 'HR_y', 'BB_x', 'BB_y', 'IBB_x', 'IBB_y', 'HBP_x', 'HBP_y', 'SO_x', 'SO_y', 'AVG_x', 'AVG_y', 'OBP_x', 'OBP_y', 'SLG_x', 'SLG_y', 'wOBA_x', 'wOBA_y'])
pitchers_combined_df = pd.merge(pitchers_combined_df, pitching_vs_right_season_df, on='Name', how='outer')
pitchers_combined_df = pitchers_combined_df.rename(columns={'Opp_OBP': 'Season_Opp_OBP_RHH', 'K_Rate' : 'Season_K%_RHH'})
pitchers_combined_df = pitchers_combined_df.drop(columns=['playerId_y','playerId_x','Season_x', 'Season_y', 'Tm_x', 'Tm_y', 'G_x', 'G_y', 'TBF_x', 'TBF_y', 'ERA_x', 'ERA_y', 'H_x', 'H_y', '2B_x', '2B_y', '3B_x', '3B_y', 'R_x', 'R_y', 'ER_x', 'ER_y', 'HR_x', 'HR_y', 'BB_x', 'BB_y', 'IBB_x', 'IBB_y', 'HBP_x', 'HBP_y', 'SO_x', 'SO_y', 'AVG_x', 'AVG_y', 'OBP_x', 'OBP_y', 'SLG_x', 'SLG_y', 'wOBA_x', 'wOBA_y'])

In [6]:
# Merge batting DataFrames together and format columns

batters_combined_df = pd.merge(batting_vs_left_year_df, batting_vs_right_year_df, on='Name', how='outer')
batters_combined_df = batters_combined_df.rename(columns={'OBP_x': 'Year_OBP_LHP', 'OBP_y': 'Year_OBP_RHP', 'K_Rate_x' : 'Year_K%_LHP', 'K_Rate_y' : 'Year_K%_RHP'})
batters_combined_df = pd.merge(batters_combined_df, batting_vs_left_season_df, on='Name', how='outer')
batters_combined_df = batters_combined_df.rename(columns={'OBP': 'Season_OBP_LHP', 'K_Rate' : 'Season_K%_LHP'})
batters_combined_df = batters_combined_df.drop(columns=['playerId_x','Season_x', 'Season_y', 'Tm_x', 'Tm_y', 'G_x', 'G_y', 'PA_x', 'PA_y', 'AB_x', 'AB_y', 'H_x', 'H_y', '1B_x', '1B_y', '2B_x', '2B_y', '3B_x', '3B_y', 'R_x', 'R_y', 'RBI_x', 'RBI_y', 'HR_x', 'HR_y', 'BB_x', 'BB_y', 'IBB_x', 'IBB_y', 'HBP_x', 'HBP_y', 'SO_x', 'SO_y', 'AVG_x', 'AVG_y', 'SF_x', 'SF_y', 'SH_x', 'SH_y', 'GDP_x', 'GDP_y', 'SB_x', 'SB_y', 'CS_x', 'CS_y'])
batters_combined_df = pd.merge(batters_combined_df, batting_vs_right_season_df, on='Name', how='outer')
batters_combined_df = batters_combined_df.rename(columns={'OBP': 'Season_OBP_RHP', 'K_Rate' : 'Season_K%_RHP'})
batters_combined_df = batters_combined_df.drop(columns=['playerId_y', 'playerId_x','Season_x', 'Season_y', 'Tm_x', 'Tm_y', 'G_x', 'G_y', 'PA_x', 'PA_y', 'AB_x', 'AB_y', 'H_x', 'H_y', '1B_x', '1B_y', '2B_x', '2B_y', '3B_x', '3B_y', 'R_x', 'R_y', 'RBI_x', 'RBI_y', 'HR_x', 'HR_y', 'BB_x', 'BB_y', 'IBB_x', 'IBB_y', 'HBP_x', 'HBP_y', 'SO_x', 'SO_y', 'AVG_x', 'AVG_y', 'SF_x', 'SF_y', 'SH_x', 'SH_y', 'GDP_x', 'GDP_y', 'SB_x', 'SB_y', 'CS_x', 'CS_y'])

In [7]:
# Read in additional CSV files from FanGraphs to retrieve handedness information for each pitcher/batter

RHH_df = pd.read_csv('RHH_data.csv')
LHH_df = pd.read_csv('LHH_data.csv')
switch_df = pd.read_csv('switch_data.csv')
RHP_df = pd.read_csv('RHP_data.csv')
LHP_df = pd.read_csv('LHP_data.csv')

In [8]:
# Initialize Handedness columns in pitching and batting DataFrames

pitchers_combined_df['Handedness'] = np.nan
batters_combined_df['Handedness'] = np.nan

# Define a helper function to update handedness

def update_handedness(RHH_df, batters_combined_df, handedness):
    for name in RHH_df['Name']:
        batters_combined_df.loc[batters_combined_df['Name'] == name, 'Handedness'] = handedness
def update_handedness(LHH_df, batters_combined_df, handedness):
    for name in LHH_df['Name']:
        batters_combined_df.loc[batters_combined_df['Name'] == name, 'Handedness'] = handedness
def update_handedness(switch_df, batters_combined_df, handedness):
    for name in switch_df['Name']:
        batters_combined_df.loc[batters_combined_df['Name'] == name, 'Handedness'] = handedness
def update_handedness(RHP_df, pitchers_combined_df, handedness):
    for name in RHP_df['Name']:
        pitchers_combined_df.loc[pitchers_combined_df['Name'] == name, 'Handedness'] = handedness
def update_handedness(LHP_df, pitchers_combined_df, handedness):
    for name in LHP_df['Name']:
        pitchers_combined_df.loc[pitchers_combined_df['Name'] == name, 'Handedness'] = handedness

# Update handedness for pitchers

update_handedness(RHP_df, pitchers_combined_df, 'R')
update_handedness(LHP_df, pitchers_combined_df, 'L')

# Update handedness for batters

update_handedness(RHH_df, batters_combined_df, 'R')
update_handedness(LHH_df, batters_combined_df, 'L')
update_handedness(switch_df, batters_combined_df, 'S')

# Display pitching DataFrame

pitchers_combined_df.head()

,Name,Year_K%_LHH,Year_Opp_OBP_LHH,Year_K%_RHH,Year_Opp_OBP_RHH,Season_K%_LHH,Season_Opp_OBP_LHH,Season_K%_RHH,Season_Opp_OBP_RHH,Handedness
0,Tommy Hunter,0.236842,0.315789,0.195652,0.326087,NaN,NaN,NaN,NaN,R
1,Matt Bush,0.240000,0.400000,0.173913,0.304348,NaN,NaN,NaN,NaN,R
2,Adam Ottavino,0.265823,0.322785,0.260163,0.256098,0.290909,0.309091,0.317073,0.231707,R
3,Matt Moore,0.176471,0.310924,0.259109,0.279352,0.157895,0.298246,0.175824,0.307692,L
4,Zack Greinke,0.136752,0.350427,0.229167,0.256944,NaN,NaN,NaN,NaN,R

In [9]:
# Display batting DataFrame

batters_combined_df.head()

,Name,Year_K%_LHP,Year_OBP_LHP,Year_K%_RHP,Year_OBP_RHP,Season_K%_LHP,Season_OBP_LHP,Season_K%_RHP,Season_OBP_RHP,Handedness
0,Miguel Cabrera,0.239583,0.354167,0.188889,0.311111,NaN,NaN,NaN,NaN,R
1,David Peralta,0.250000,0.363636,0.170732,0.286031,0.222222,0.555556,0.194444,0.277778,L
2,Adam Wainwright,0.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,R
3,Carlos Santana,0.144628,0.351240,0.172166,0.311334,0.171053,0.342105,0.156780,0.317797,S
4,Nelson Cruz,0.325581,0.290698,0.274194,0.290323,NaN,NaN,NaN,NaN,R

In [10]:
# Input starting pitcher and opposing team's lineup

pitcher_name = input("Enter the name of the starting pitcher: ")
batter_1 = input("Enter the name of the first batter: ")
batter_2 = input("Enter the name of the second batter: ")
batter_3 = input("Enter the name of the third batter: ")
batter_4 = input("Enter the name of the fourth batter: ")
batter_5 = input("Enter the name of the fifth batter: ")
batter_6 = input("Enter the name of the sixth batter: ")
batter_7 = input("Enter the name of the seventh batter: ")
batter_8 = input("Enter the name of the eighth batter: ")
batter_9 = input("Enter the name of the ninth batter: ")

Enter the name of the starting pitcher: Joe Ryan
Enter the name of the first batter: Jorge Soler
Enter the name of the second batter: LaMonte Wade Jr.
Enter the name of the third batter: Heliot Ramos
Enter the name of the fourth batter: Patrick Bailey
Enter the name of the fifth batter: Matt Chapman
Enter the name of the sixth batter: Michael Conforto
Enter the name of the seventh batter: Thairo Estrada
Enter the name of the eighth batter: Mike Yastrzemski
Enter the name of the ninth batter: Brett Wisely

In [11]:
# Store inputted batter names as strings

batter_names = [str(batter_1), str(batter_2), str(batter_3), str(batter_4), str(batter_5), str(batter_6), str(batter_7), str(batter_8), str(batter_9)]

In [12]:
# Pull relevant names for combined pitching/batting DataFrame

pitcher_data = pitchers_combined_df[pitchers_combined_df['Name'] == pitcher_name]
batter_data = batters_combined_df[batters_combined_df['Name'].isin(batter_names)]

# Order batter data by lineup

batter_data['batting_order'] = pd.Categorical(batter_data['Name'], categories=batter_names, ordered=True)
batter_data = batter_data.sort_values('batting_order').drop(columns='batting_order')

# Concatenate data vertically to stack rows and create combined DataFrame of starting pitcher and opposing team's lineup

model_data = pd.concat([pitcher_data, batter_data], axis=0, ignore_index=True)
model_data
model_data.head()

/var/folders/_0/z435wnvn6236c4cm5wmb3_4w0000jc/T/ipykernel_51876/2701384632.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  batter_data['batting_order'] = pd.Categorical(batter_data['Name'], categories=batter_names, ordered=True)

,Name,Year_K%_LHH,Year_Opp_OBP_LHH,Year_K%_RHH,Year_Opp_OBP_RHH,Season_K%_LHH,Season_Opp_OBP_LHH,Season_K%_RHH,Season_Opp_OBP_RHH,Handedness,Year_K%_LHP,Year_OBP_LHP,Year_K%_RHP,Year_OBP_RHP,Season_K%_LHP,Season_OBP_LHP,Season_K%_RHP,Season_OBP_RHP
0,Joe Ryan,0.32,0.25,0.336323,0.282511,0.346667,0.24,0.320513,0.25641,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jorge Soler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,0.232456,0.381579,0.248132,0.309417,0.247312,0.365591,0.242991,0.280374
2,LaMonte Wade Jr.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,0.213592,0.378641,0.192751,0.393740,0.095238,0.523810,0.213836,0.440252
3,Heliot Ramos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,0.267857,0.401786,0.284946,0.306452,0.212121,0.515152,0.284884,0.313953
4,Patrick Bailey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S,0.264516,0.341935,0.247140,0.292906,0.268293,0.317073,0.198925,0.333333

In [13]:
# Input home plate umpire's career K rate

#umpire_K_rate = float(input("Enter the home plate umpire's average career K rate: "))

# Display league-wide K rate in 2024 season

#mlb_K_rate = mlb_season_df.loc[mlb_season_df['League'] == 'MLB', 'K_Rate'].values[0]
#mlb_K_rate

In [14]:
# Subtract umpire's career K rate from league-wide K rate to calculate umpire factor

#umpire_data = mlb_K_rate - umpire_K_rate

In [15]:
# Combine two sample sizes (beginning of 2023 season - present and beginning of 2024 - present), placing 50% more weight on 2024 season

def get_combined_stat(season_stat, year_stat, weight=0.5):
    if pd.isna(season_stat):
        return year_stat
    if pd.isna(year_stat):
        return season_stat
    return (weight * season_stat) + ((1 - weight) * year_stat)

# Initialize inning simulation model with 10,000 sims

def simulate_inning(pitchers_data, batters_data, n_simulations=10000):
    
    # Variable for number of times zero strikeouts occur
    
    no_strikeout_counts = 0
    
    # Pull pitcher handedness information
    
    pitcher_handedness = pitchers_data['Handedness']
    
    # Loop through sims for each batter, terminating the sim when 3 outs occur
    
    for _ in range(n_simulations):
        outs = 0
        strikeouts = 0
        for idx, batter in batters_data.iterrows():
            if outs >= 3:
                break
            
            # Pull batter handedness information
            
            batter_handedness = batter['Handedness']
            
            # Determine handedness matchup for each batter
            
            if batter_handedness == 'L':
                if pitcher_handedness == 'R':
                    batter_season_k_rate = batter['Season_K%_RHP']
                    batter_year_k_rate = batter['Year_K%_RHP']
                    batter_season_obp = batter['Season_OBP_RHP']
                    batter_year_obp = batter['Year_OBP_RHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_LHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_LHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_LHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_LHH']
                else:
                    batter_season_k_rate = batter['Season_K%_LHP']
                    batter_year_k_rate = batter['Year_K%_LHP']
                    batter_season_obp = batter['Season_OBP_LHP']
                    batter_year_obp = batter['Year_OBP_LHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_LHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_LHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_LHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_LHH']
            elif batter_handedness == 'R':
                if pitcher_handedness == 'R':
                    batter_season_k_rate = batter['Season_K%_RHP']
                    batter_year_k_rate = batter['Year_K%_RHP']
                    batter_season_obp = batter['Season_OBP_RHP']
                    batter_year_obp = batter['Year_OBP_RHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_RHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_RHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_RHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_RHH']
                else:
                    batter_season_k_rate = batter['Season_K%_LHP']
                    batter_year_k_rate = batter['Year_K%_LHP']
                    batter_season_obp = batter['Season_OBP_LHP']
                    batter_year_obp = batter['Year_OBP_LHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_RHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_RHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_RHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_RHH']
                    
            # Switch hitter
            
            else:
                if pitcher_handedness == 'R':
                    batter_season_k_rate = batter['Season_K%_RHP']
                    batter_year_k_rate = batter['Year_K%_RHP']
                    batter_season_obp = batter['Season_OBP_RHP']
                    batter_year_obp = batter['Year_OBP_RHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_LHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_LHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_LHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_LHH']
                else:
                    batter_season_k_rate = batter['Season_K%_LHP']
                    batter_year_k_rate = batter['Year_K%_LHP']
                    batter_season_obp = batter['Season_OBP_LHP']
                    batter_year_obp = batter['Year_OBP_LHP']
                    
                    pitcher_season_k_rate = pitchers_data['Season_K%_RHH']
                    pitcher_year_k_rate = pitchers_data['Year_K%_RHH']
                    pitcher_season_obp = pitchers_data['Season_Opp_OBP_RHH']
                    pitcher_year_obp = pitchers_data['Year_Opp_OBP_RHH']
            
            # Calculate combined K rate and on-base percentages for each at-bat
            
            combined_k_rate = get_combined_stat(batter_season_k_rate, batter_year_k_rate)
            combined_k_rate = (combined_k_rate + get_combined_stat(pitcher_season_k_rate, pitcher_year_k_rate)) / 2
            combined_obp = get_combined_stat(batter_season_obp, batter_year_obp)
            combined_obp = (combined_obp + get_combined_stat(pitcher_season_obp, pitcher_year_obp)) / 2
            
            # Determine if batter strikes out
            
            if np.random.rand() < combined_k_rate:
                strikeouts += 1
                outs += 1
                
            # Determine if batter gets on base (H, BB, or HBP)
            
            elif np.random.rand() < combined_obp:
            
                # Batter gets on base
                
                continue
                
            # Otherwise, batter is out via batted out
            
            else:
                outs += 1
                
        # Add 1 to "no strikeout" count if applicable
        
        if strikeouts == 0:
            no_strikeout_counts += 1
            
    # Return rate of "no strikeout" occurrences in 10,000 sims
    
    return no_strikeout_counts / n_simulations

# Separate pitcher data and batter data

pitchers_data = model_data.iloc[0]
batters_data = model_data.iloc[1:]

# Run the simulation and display estimated probability of no strikeouts occurring in decimal form

probability_no_strikeouts = simulate_inning(pitchers_data, batters_data)
print(f"Estimated Probability of Zero Strikeouts: {probability_no_strikeouts:.4f}")

Estimated Probability of Zero Strikeouts: 0.2636